### ISSUE TITLE
Upgrading to Gtk 3.22

### ISSUE THREAD

**Issue by EPashkin** [gtk-rs/gir-files#1]
I tried update `gir-files` with ubuntu's latest (like http://packages.ubuntu.com/zesty/amd64/libgtk-3-dev).
Examples with feature `gtk_3_18` build fine, but I can't build version depends on `gtk/v3_18` as no package with these features published.
So I starting make PRs for prepare these packages, not sure that it time for publish new crates (maybe we need solve other needed problem).
@GuillaumeGomez, how you think?

**Comment by EPashkin** [comment]
In all preview PR's I include to commit "Regen test" only files with significant changes

**Comment by EPashkin** [comment]
All preview PR's added

**Comment by EPashkin** [comment]
@GuillaumeGomez, To start make working PR's I need https://github.com/gtk-rs/gir/pull/294 merged first.

**Comment by EPashkin** [comment]
Ok, I start update PR's
All generated code must have `// This file was generated by gir (5e8c56e) from gir-files (71d73f0)`

**Comment by GuillaumeGomez** [comment]
@EPashkin: Sorry, didn't see your issue in here. I think we'll release the new crates version after this update. A lot of changes have been done since last time and a number of people asked for it too.

**Comment by EPashkin** [comment]
@GuillaumeGomez next we need publish all crates and after that merge updated examples features and finally update travis scripts (not sure to 3.22 or lower).

**Comment by GuillaumeGomez** [comment]
Unfortunately, I didn't work much on travis side. :-/ Without @gkoz we're a bit stuck so we'll have to try out.

Do you want to update crates' version or do you want me to do it?

**Comment by EPashkin** [comment]
> Unfortunately, I didn't work much on travis side. :-/ Without @gkoz we're a bit stuck so we'll have to try out.
Do you want to update crates' version or do you want me to do it?

@GuillaumeGomez, I missed this comment yesterday.
If by `update crates version` you mean prepare to publish, it on you, as I know nothing about publishing process

**Comment by GuillaumeGomez** [comment]
Ok, I'll take care of it today.

**Comment by EPashkin** [comment]
Seems all done for this issue
