### ISSUE TITLE
Add `webkit2gtk5-rs` files

### ISSUE THREAD

**Issue by emmyoh** [gtk-rs/gir-files#101]
To help aid development on [`webkit2gtk5-rs`](https://gitlab.gnome.org/World/Rust/webkit2gtk5-rs), I propose that the following files be included in this repository (by including them within `dl.py`):

  - `WebKit2-5.0.gir`
  - `JavaScriptCore-5.0.gir`
  - `Soup-3.0.gir`
  - `WebKit2WebExtension-5.0.gir`

Additionally, to properly patch `JavaScriptCore-5.0.gir`, two more files will be needed:
  - [`JavaScriptCore-5.0-patch.gir`](https://gitlab.gnome.org/World/Rust/webkit2gtk5-rs/-/blob/d015608084f01973f25094001a2bc4e10686cf8d/webkit2gtk-gir-files/JavaScriptCore-5.0-patch.gir)
  - [`JavaScriptCore-5.0.xsl`](https://gitlab.gnome.org/World/Rust/webkit2gtk5-rs/-/blob/d015608084f01973f25094001a2bc4e10686cf8d/webkit2gtk-gir-files/JavaScriptCore-5.0.xsl)

To patch `JavaScriptCore-5.0.gir`, `fix.sh` should have the following appended to it:
```shell
# change int to uint to prevent overflow
xmlstarlet ed -L \
	-u '//_:constant[@name="DOM_NODE_FILTER_SHOW_ALL"]/_:type[@name="gint"]/@c:type' -v "guint" \
	-u '//_:constant[@name="DOM_NODE_FILTER_SHOW_ALL"]/_:type[@name="gint"]/@name' -v "guint" \
	WebKit2WebExtension-5.0.gir

xmlstarlet tr JavaScriptCore-5.0.xsl JavaScriptCore-5.0.gir | xmlstarlet fo >JavaScriptCore-5.0.gir.tmp
mv JavaScriptCore-5.0.gir.tmp JavaScriptCore-5.0.gir

# fill in types from JavaScriptCore
xmlstarlet ed -L \
	-i '///_:type[not(@name) and @c:type="JSGlobalContextRef"]' -t 'attr' -n 'name' -v "JavaScriptCore.GlobalContextRef" \
	-i '///_:type[not(@name) and @c:type="JSValueRef"]' -t 'attr' -n 'name' -v "JavaScriptCore.ValueRef" \
	WebKit2WebExtension-5.0.gir WebKit2-5.0.gir

xmlstarlet ed -L \
	-u '//_:constant[@name="DOM_NODE_FILTER_SHOW_ALL"]/_:type/@name' -v "guint" \
	-u '//_:constant[@name="DOM_NODE_FILTER_SHOW_ALL"]/_:type/@c:type' -v "guint" \
	WebKit2WebExtension-5.0.gir
```

---

With all this in mind, would it make sense to add the `webkit2gtk-5.0` .GIR files to this repository? Would it be beyond the scope of this repository to do so? If not, should this repository go so far as to simply contain all the .GIR files included within the GNOME SDK (as [this repository does](https://github.com/emmyoh/gir-files-webkit2gtk))?

**Comment by sdroege** [comment]
Why should they be included here instead of inside the webkit2gtk5-rs repository?

**Comment by emmyoh** [comment]
The `webkit2gtk5-rs` repository is not updated nearly as often, and would greatly benefit from the auto-updating taking place in this repository. While I did write the original workflow for this repository, I'm only familiar with GitHub Actions and I'm not sure how to build a similar workflow for a GitLab instance.

If the `webkit2gtk5-rs` repository includes the latest .GIR files (via a Git submodule), then the bindings can be regenerated when necessary, without having to also manually grab & patch the latest .GIR files, as has been necessary so far.

**Comment by GuillaumeGomez** [comment]
You don't need to have the gir files in this repository directly. If your issue is about updates, you can just take our scripts and our github actions config.

We just removed `webkit2gtk` from this organization so there isn't much point for us to put back `webkit2gtk` "items" in here.

**Comment by emmyoh** [comment]
Sure, I understand :+1:

**Comment by GuillaumeGomez** [comment]
If you need help to set things up, don't hesitate to ask us though. Not supporting it ourselves doesn't mean we can't help. ;)

**Comment by emmyoh** [comment]
Thanks. Hopefully I'll be able to get things set up by myself, but, thank you
