### ISSUE TITLE
How to generate a GIR file?

### ISSUE THREAD

**Issue by Boiethios** [gtk-rs/gir-files#38]
I am not sure where I should open this issue, but I cannot see any documentation about how to create a new GIR file.

I would like to create a Rust binding of [libgoa](https://wiki.gnome.org/Projects/GnomeOnlineAccounts) and I was told that using GIR is a good first step. But I only saw some documentation about *using* a GIR file, not _generating_ it.

BTW, does the GIR format handle the asynchronous methods? In my binding, I wrap the asynchronous Rust methods in a `fn foobar() -> impl Future<Output = FooBar>`, but I wonder if GIR does that as well.

**Comment by bilelmoussaoui** [comment]
GIR files are usually generated when building the library, you might have to enable some build time option for it and it requires some dependencies installed on your machine. 

And yes, we do support generating async functions.
