### ISSUE TITLE
Soup-2.4.gir has gconstpointer instead of the actual type for a couple functions

### ISSUE THREAD

**Issue by Vypo** [gtk-rs/gir-files#78]
For example:

 - [`soup_address_equal_by_ip`](https://github.com/gtk-rs/gir-files/blob/6088bb634a406402f308f01d2f33067951d5095b/Soup-2.4.gir#L326)
 - [`soup_address_equal_by_name`](https://github.com/gtk-rs/gir-files/blob/6088bb634a406402f308f01d2f33067951d5095b/Soup-2.4.gir#L364)

**Comment by sdroege** [comment]
That's something to report to https://gitlab.gnome.org/GNOME/libsoup
