### ISSUE TITLE
libadwaita.gir

### ISSUE THREAD

**Issue by richardanaya** [gtk-rs/gir-files#79]
Hey all, i'm really interested in getting the new adwaita project into Rust.  I thought i'd open this issue as a place to kickstart the effort. Maybe folks have thoughts about this library and a strategy for inclusion.

**Comment by sdroege** [comment]
That already has bindings here: https://gitlab.gnome.org/bilelmoussaoui/libadwaita-rs

CC @bilelmoussaoui :)
